// ── social.js (Mare App 6, v82) — social media publishing ─────────────
// Ported from Per App's publishers layer (publishers/bulkpublish.js +
// index.js), adapted for Mare:
//   - BulkPublish does the actual posting (Facebook, Instagram, Threads,
//     LinkedIn…). Mare has its own organization there with its own API
//     key (Railway: BULKPUBLISH_API_KEY on the Mare service).
//   - Mare posts ONLY to the channels chosen in Admin, by their exact
//     BulkPublish id. A platform with no chosen channel refuses to post
//     with a clear message rather than guessing (Per App used to take the
//     first channel of that platform — unsafe with a shared account).
//   - A queue with set times, a 'next free slot' from each platform's
//     posting times, and a scheduler that publishes what is due.
//   - Only staff-uploaded media (folder social/) can go on a post: nothing
//     a child made can be attached to a public post.
//   - "Image/Video generated by AI." is added only when the person posting
//     ticks that the picture/video is AI-made (Mare's illustrations and
//     photos aren't, so it isn't automatic as in Per App).
//
// Tables: social_queue (one row per post: queued / published / failed),
//         social_times (posting days and times per platform).
// Setting: app_config.social_channels_json { platform: channelId }.

const crypto = require('crypto');
const BP = 'https://app.bulkpublish.com/api';
const PLATFORMS = ['facebook', 'instagram', 'threads', 'linkedin'];
const TZ = 'Europe/Amsterdam'; // posting times are local NL/BE time (Mare's audience)

function register(app, { db, auth, media }) {
  const configured = () => !!process.env.BULKPUBLISH_API_KEY;

  async function bp(method, path, body) {
    const key = process.env.BULKPUBLISH_API_KEY;
    if (!key) throw new Error('BulkPublish is not set up yet: add BULKPUBLISH_API_KEY (from the Mare organization) in Railway.');
    const res = await fetch(`${BP}${path}`, { method, headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      const raw = data && (data.error || data.message);
      throw new Error((raw && (typeof raw === 'string' ? raw : raw.message || JSON.stringify(raw))) || `BulkPublish returned ${res.status}`);
    }
    return data;
  }

  // every channel this key can see (cached a minute)
  let cache = { at: 0, list: [] };
  async function channels(fresh) {
    if (!configured()) return [];
    if (!fresh && Date.now() - cache.at < 60000) return cache.list;
    const { channels: list } = await bp('GET', '/channels');
    cache = { at: Date.now(), list: (list || []).map(c => ({ id: String(c.id), platform: String(c.platform || '').toLowerCase(), bpPlatform: c.platform, bpId: c.id, name: c.name || c.username || c.platform })) };
    return cache.list;
  }
  const chosen = () => { try { return JSON.parse((db.getRow(`SELECT social_channels_json AS j FROM app_config WHERE id = 'default'`) || {}).j || '{}') || {}; } catch { return {}; } };

  async function uploadMedia(key) {
    const url = await media.getPlaybackUrl(key);
    const fileRes = await fetch(url);
    if (!fileRes.ok) throw new Error(`Could not read the picture/video (${fileRes.status}).`);
    const type = (fileRes.headers.get('content-type') || 'application/octet-stream').split(';')[0];
    const form = new FormData();
    form.append('file', new Blob([Buffer.from(await fileRes.arrayBuffer())], { type }), key.split('/').pop());
    const up = await fetch(`${BP}/media`, { method: 'POST', headers: { Authorization: `Bearer ${process.env.BULKPUBLISH_API_KEY}` }, body: form });
    const data = await up.json().catch(() => ({}));
    if (!up.ok || !data.file || !data.file.id) throw new Error((data && (data.error && (data.error.message || data.error))) || `BulkPublish media upload returned ${up.status}`);
    return data.file.id;
  }
  const MEDIA_TYPES = { instagram: { image: 'feed_photo', video: 'feed_video' }, threads: { image: 'image', video: 'video' } };

  // Publish one post now, to the chosen channel only.
  async function publish(platform, { content, mediaKey, mediaType, aiMedia }) {
    const id = chosen()[platform];
    if (!id) throw new Error(`No ${platform} channel is chosen for Mare yet (Sales & Marketing → Social channels).`);
    const ch = (await channels()).find(c => c.id === String(id)) || (await channels(true)).find(c => c.id === String(id));
    if (!ch) throw new Error(`The chosen ${platform} channel (id ${id}) isn't connected in Mare's BulkPublish organization any more.`);
    let text = String(content || '').trim();
    if (mediaKey && aiMedia) text = `${text}\n\n${mediaType === 'video' ? 'Video generated by AI.' : 'Image generated by AI.'}`.trim();
    const body = { content: text, channels: [{ channelId: ch.bpId, platform: ch.bpPlatform }] /* exactly as BulkPublish gave them, like Per App */, status: 'scheduled', scheduledAt: new Date(Date.now() + 10000).toISOString() };
    if (mediaKey) {
      body.mediaFiles = [await uploadMedia(mediaKey)];
      const o = MEDIA_TYPES[platform] && MEDIA_TYPES[platform][mediaType === 'video' ? 'video' : 'image'];
      if (o) body.postTypeOverrides = { [platform]: o };
    }
    const r = await bp('POST', '/posts', body);
    return { id: (r && r.post && r.post.id) || (r && r.id) || null, channelId: ch.id };
  }

  // ── posting times and the next free slot ──
  const times = () => {
    const out = {};
    for (const p of PLATFORMS) out[p] = { days: [2, 3, 4], times: ['09:00'] };
    for (const r of db.allRows(`SELECT platform, days, times FROM social_times`)) { try { out[r.platform] = { days: JSON.parse(r.days), times: JSON.parse(r.times) }; } catch { /* keep default */ } }
    return out;
  };
  // UTC instant for a local date + HH:MM in TZ
  function zoned(ymd, hm) {
    const [y, m, d] = ymd.split('-').map(Number), [H, M] = hm.split(':').map(Number);
    let ts = Date.UTC(y, m - 1, d, H, M);
    for (let i = 0; i < 2; i++) {
      const parts = Object.fromEntries(new Intl.DateTimeFormat('en-GB', { timeZone: TZ, hourCycle: 'h23', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).formatToParts(new Date(ts)).map(p => [p.type, p.value]));
      const shown = Date.UTC(+parts.year, +parts.month - 1, +parts.day, +parts.hour, +parts.minute);
      ts += Date.UTC(y, m - 1, d, H, M) - shown;
    }
    return new Date(ts);
  }
  function nextSlot(platform) {
    const cfg = times()[platform] || { days: [2, 3, 4], times: ['09:00'] };
    const taken = new Set(db.allRows(`SELECT scheduled_for FROM social_queue WHERE platform = ? AND status = 'queued'`, [platform]).map(r => r.scheduled_for));
    const slots = (cfg.times || []).filter(x => /^\d\d:\d\d$/.test(x)).sort();
    if (!slots.length || !(cfg.days || []).length) return new Date(Date.now() + 15 * 60000).toISOString();
    for (let k = 0; k < 120; k++) {
      const day = new Date(Date.now() + k * 864e5);
      const ymd = new Intl.DateTimeFormat('en-CA', { timeZone: TZ }).format(day);
      const dow = new Date(ymd + 'T12:00:00Z').getUTCDay();
      if (!cfg.days.includes(dow)) continue;
      for (const hm of slots) {
        const at = zoned(ymd, hm);
        if (at.getTime() < Date.now() + 5 * 60000) continue;
        const iso = at.toISOString();
        if (!taken.has(iso)) return iso;
      }
    }
    return new Date(Date.now() + 15 * 60000).toISOString();
  }

  // ── the queue ──
  const KEY_OK = /^social\/[A-Za-z0-9._\-\/]+$/;
  function cleanPost(b, partial) {
    const f = {};
    if (!partial || b.platform !== undefined) { if (!PLATFORMS.includes(b.platform)) throw new Error('Choose a platform.'); f.platform = b.platform; }
    if (!partial || b.content !== undefined) { const c = String(b.content || '').trim(); if (!c) throw new Error('The post has no text.'); f.content = c.slice(0, 5000); }
    if (b.mediaKey !== undefined) {
      if (b.mediaKey && !KEY_OK.test(b.mediaKey)) throw new Error('Only pictures or videos uploaded for social posts can be attached.');
      f.media_key = b.mediaKey || null;
      f.media_type = b.mediaKey ? (b.mediaType === 'video' ? 'video' : 'image') : null;
    }
    if (b.aiMedia !== undefined) f.ai_media = b.aiMedia ? 1 : 0;
    if (b.scheduledFor !== undefined) {
      const t = b.scheduledFor === 'next' ? null : Date.parse(b.scheduledFor);
      f.scheduled_for = b.scheduledFor === 'next' ? 'next' : (Number.isFinite(t) ? new Date(t).toISOString() : null);
      if (!f.scheduled_for) throw new Error('Choose when to post.');
    }
    return f;
  }
  const row = (id) => db.getRow(`SELECT * FROM social_queue WHERE id = ?`, [id]);
  async function sendRow(r) {
    try {
      const out = await publish(r.platform, { content: r.content, mediaKey: r.media_key, mediaType: r.media_type, aiMedia: !!r.ai_media });
      db.runBatch([[`UPDATE social_queue SET status = 'published', published_at = ?, bp_post_id = ?, channel_id = ?, error = NULL WHERE id = ?`, [new Date().toISOString(), out.id, out.channelId, r.id]]]);
      return { ok: true };
    } catch (e) {
      db.runBatch([[`UPDATE social_queue SET status = 'failed', error = ? WHERE id = ?`, [String(e.message || e).slice(0, 400), r.id]]]);
      return { ok: false, error: e.message };
    }
  }
  // scheduler: every 2 minutes, publish what is due (one at a time)
  let running = false;
  async function runDue() {
    if (running || !configured()) return;
    running = true;
    try {
      const due = db.allRows(`SELECT * FROM social_queue WHERE status = 'queued' AND scheduled_for <= ? ORDER BY scheduled_for LIMIT 10`, [new Date().toISOString()]);
      for (const r of due) {
        db.runBatch([[`UPDATE social_queue SET status = 'sending' WHERE id = ? AND status = 'queued'`, [r.id]]]);
        await sendRow(r);
      }
    } catch (e) { console.error('social queue run failed:', e.message); }
    finally { running = false; }
  }
  setInterval(runDue, 2 * 60 * 1000).unref();
  // a post left 'sending' by a restart goes back in the queue
  setTimeout(() => { try { db.runBatch([[`UPDATE social_queue SET status = 'queued' WHERE status = 'sending'`, []]]); } catch { /* table may not exist yet */ } }, 5000).unref();

  const staff = auth.requireAuthApi(['admin', 'support']);
  const adminOnly = auth.requireAuthApi(['admin']);
  const fail = (res, e, code) => res.status(code || 400).json({ error: e.message || String(e) });

  // channels: what the key sees, what is chosen, what isn't
  app.get('/api/admin/social/status', staff, async (req, res) => {
    const choice = chosen();
    let list = [], error = null;
    try { list = await channels(req.query.fresh === '1'); } catch (e) { error = e.message; }
    const chosenIds = new Set(Object.values(choice).filter(Boolean).map(String));
    res.json({
      configured: configured(), error, platforms: PLATFORMS, channels: list, chosen: choice,
      health: PLATFORMS.map(p => ({ platform: p, id: choice[p] || null, ok: !!(choice[p] && list.some(c => c.id === String(choice[p]))) })),
      notChosen: list.filter(c => !chosenIds.has(c.id)),
      times: times(),
    });
  });
  app.put('/api/admin/social/channels', adminOnly, async (req, res) => {
    try {
      const list = await channels(true);
      const out = {};
      for (const p of PLATFORMS) {
        const id = req.body && req.body[p] ? String(req.body[p]) : '';
        if (!id) continue;
        const ch = list.find(c => c.id === id);
        if (!ch) throw new Error(`Channel ${id} isn't visible to Mare's BulkPublish key.`);
        if (ch.platform !== p) throw new Error(`Channel ${id} is on ${ch.bpPlatform || ch.platform}, not ${p}.`);
        out[p] = id;
      }
      db.runBatch([[`UPDATE app_config SET social_channels_json = ? WHERE id = 'default'`, [JSON.stringify(out)]]]);
      res.json({ ok: true, chosen: out });
    } catch (e) { fail(res, e); }
  });
  app.put('/api/admin/social/times', adminOnly, (req, res) => {
    try {
      const list = [];
      for (const p of PLATFORMS) {
        const v = req.body && req.body[p]; if (!v) continue;
        const days = [...new Set((v.days || []).map(Number).filter(d => d >= 0 && d <= 6))].sort();
        const ts = [...new Set((v.times || []).map(String).map(s => s.trim()).filter(s => /^([01]\d|2[0-3]):[0-5]\d$/.test(s)))].sort().slice(0, 6);
        list.push([`INSERT INTO social_times (platform, days, times) VALUES (?,?,?) ON CONFLICT(platform) DO UPDATE SET days = excluded.days, times = excluded.times`, [p, JSON.stringify(days), JSON.stringify(ts)]]);
      }
      db.runBatch(list);
      res.json({ ok: true, times: times() });
    } catch (e) { fail(res, e); }
  });

  // queue
  app.get('/api/admin/social/queue', staff, async (req, res) => {
    const rows = db.allRows(`SELECT * FROM social_queue WHERE status IN ('queued','sending') OR created_at >= datetime('now','-120 days') ORDER BY CASE WHEN status IN ('queued','sending') THEN 0 ELSE 1 END, CASE WHEN status IN ('queued','sending') THEN scheduled_for END ASC, COALESCE(published_at, created_at) DESC LIMIT 300`);
    const out = [];
    for (const r of rows) {
      let mediaUrl = null;
      if (r.media_key) { try { mediaUrl = await media.getPlaybackUrl(r.media_key); } catch { /* no preview */ } }
      out.push({ ...r, mediaUrl });
    }
    res.json({ posts: out, configured: configured() });
  });
  app.post('/api/admin/social/queue', staff, (req, res) => {
    try {
      const f = cleanPost(req.body || {}, false);
      if (!f.scheduled_for || f.scheduled_for === 'next') f.scheduled_for = nextSlot(f.platform);
      const id = crypto.randomUUID();
      db.runBatch([[`INSERT INTO social_queue (id, platform, content, media_key, media_type, ai_media, status, scheduled_for, created_by) VALUES (?,?,?,?,?,?, 'queued', ?, ?)`,
        [id, f.platform, f.content, f.media_key || null, f.media_type || null, f.ai_media || 0, f.scheduled_for, req.user.id]]]);
      res.json({ ok: true, id, scheduledFor: f.scheduled_for });
    } catch (e) { fail(res, e); }
  });
  app.patch('/api/admin/social/queue/:id', staff, (req, res) => {
    try {
      const r = row(req.params.id); if (!r) return res.status(404).json({ error: 'Not found' });
      if (r.status === 'published' || r.status === 'sending') throw new Error('This post has already gone out.');
      const f = cleanPost(req.body || {}, true);
      if (f.scheduled_for === 'next') f.scheduled_for = nextSlot(f.platform || r.platform);
      const sets = Object.keys(f);
      if (r.status === 'failed' && f.scheduled_for) { sets.push('status'); f.status = 'queued'; }
      if (sets.length) db.runBatch([[`UPDATE social_queue SET ${sets.map(k => `${k} = ?`).join(', ')}, error = CASE WHEN ? THEN NULL ELSE error END WHERE id = ?`, [...sets.map(k => f[k]), f.status ? 1 : 0, r.id]]]);
      res.json({ ok: true });
    } catch (e) { fail(res, e); }
  });
  app.delete('/api/admin/social/queue/:id', staff, (req, res) => {
    const r = row(req.params.id); if (!r) return res.status(404).json({ error: 'Not found' });
    if (r.status === 'sending') return res.status(409).json({ error: 'This post is being sent right now.' });
    db.runBatch([[`DELETE FROM social_queue WHERE id = ?`, [r.id]]]);
    res.json({ ok: true });
  });
  app.post('/api/admin/social/queue/:id/publish-now', staff, async (req, res) => {
    const r = row(req.params.id); if (!r) return res.status(404).json({ error: 'Not found' });
    if (r.status === 'published' || r.status === 'sending') return res.status(409).json({ error: 'This post has already gone out.' });
    db.runBatch([[`UPDATE social_queue SET status = 'sending' WHERE id = ?`, [r.id]]]);
    const out = await sendRow(r);
    if (!out.ok) return res.status(502).json({ error: out.error });
    res.json({ ok: true });
  });
  // publish straight away (from the generator): kept in the list as published or failed
  app.post('/api/admin/social/publish', staff, async (req, res) => {
    try {
      const f = cleanPost({ ...(req.body || {}), scheduledFor: undefined }, false);
      const id = crypto.randomUUID();
      db.runBatch([[`INSERT INTO social_queue (id, platform, content, media_key, media_type, ai_media, status, scheduled_for, created_by) VALUES (?,?,?,?,?,?, 'sending', ?, ?)`,
        [id, f.platform, f.content, f.media_key || null, f.media_type || null, f.ai_media || 0, new Date().toISOString(), req.user.id]]]);
      const out = await sendRow(row(id));
      if (!out.ok) return res.status(502).json({ error: out.error });
      res.json({ ok: true, id });
    } catch (e) { fail(res, e); }
  });

  return { publish, runDue, nextSlot };
}

module.exports = { register, PLATFORMS };
